# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Beenius' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Beenius

  target 'BeeniusTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BeeniusUITests' do
    # Pods for testing
  end

end
