# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Beenius' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Beenius
   pod 'SnapKit'
   pod 'SwiftLint'
   pod 'Alamofire', '~> 5.0.0-beta.6'
   pod 'Kingfisher' 
  
  target 'BeeniusTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BeeniusUITests' do
    # Pods for testing
  end

end
